export const fallbackProjects = [
  {
    id: 'fallback-courtyard-house',
    title: 'The Courtyard House',
    description: 'A home shaped by natural light, honest materials, and the rhythms of everyday life.',
    location: 'Whitefield, Bengaluru',
    category: 'Residential',
    status: 'Completed',
    cover_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85',
  },
  {
    id: 'fallback-nirvana-workspace',
    title: 'Nirvana Workspace',
    description: 'A calm, adaptable workplace for a growing creative team.',
    location: 'Indiranagar, Bengaluru',
    category: 'Commercial',
    status: 'Completed',
    cover_image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85',
  },
  {
    id: 'fallback-terracotta-villa',
    title: 'Illustrative Concept: Terracotta Courtyard Villa',
    description: 'A residential concept exploring shaded courtyards, textured brick, and generous daylight.',
    location: 'Bengaluru (Illustrative)',
    category: 'Residential',
    status: 'Planned',
    cover_image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=82',
  },
  {
    id: 'fallback-garden-house',
    title: 'Illustrative Concept: Garden House',
    description: 'An independent-house concept shaped around a planted court and calm, practical living spaces.',
    location: 'Bengaluru (Illustrative)',
    category: 'Residential',
    status: 'Planned',
    cover_image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=82',
  },
  {
    id: 'fallback-urban-apartment',
    title: 'Illustrative Concept: Urban Apartment Living',
    description: 'A premium apartment interior concept using warm finishes and clear, flexible zones.',
    location: 'Bengaluru (Illustrative)',
    category: 'Residential',
    status: 'Planned',
    cover_image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=82',
  },
  {
    id: 'fallback-lightwell-offices',
    title: 'Illustrative Concept: Lightwell Studio Offices',
    description: 'A modern office concept with shared work areas, quiet rooms, and daylight-led planning.',
    location: 'Bengaluru (Illustrative)',
    category: 'Commercial',
    status: 'Planned',
    cover_image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82',
  },
  {
    id: 'fallback-civic-corner',
    title: 'Illustrative Concept: Civic Corner Building',
    description: 'Illustrative demo only; not a completed or commissioned Srinidhi Constructions project. A commercial-building study focused on a legible street frontage and adaptable floor plates.',
    location: 'Bengaluru (Illustrative)',
    category: 'Commercial',
    status: 'Planned',
    cover_image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82',
  },
  {
    id: 'fallback-material-study',
    title: 'Illustrative Concept: Material Study Interior',
    description: 'Illustrative demo only; not a completed or commissioned Srinidhi Constructions project. An interior-design study balancing natural materials, restrained detailing, and everyday function.',
    location: 'Bengaluru (Illustrative)',
    category: 'Planning',
    status: 'Planned',
    cover_image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=82',
  },
  {
    id: 'fallback-passive-light-residence',
    title: 'Illustrative Concept: Passive Light Residence',
    description: 'Illustrative demo only; not a completed or commissioned Srinidhi Constructions project. A sustainable-architecture concept considering daylight, shade, and lower-impact material choices.',
    location: 'Bengaluru (Illustrative)',
    category: 'Planning',
    status: 'Planned',
    cover_image: 'https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1400&q=82',
  },
  {
    id: 'fallback-home-renewed',
    title: 'Illustrative Concept: A Home Renewed',
    description: 'Illustrative demo only; not a completed or commissioned Srinidhi Constructions project. A renovation concept exploring how an existing home can be adapted with careful planning and a lighter touch.',
    location: 'Bengaluru (Illustrative)',
    category: 'Renovation',
    status: 'Planned',
    cover_image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=82',
  },
]

export const fallbackServices = [
  {
    id: 'fallback-residential-construction',
    title: 'Residential construction',
    description: 'Homes shaped around the way you live, with considered materials and an honest build process.',
  },
  {
    id: 'fallback-commercial-spaces',
    title: 'Commercial spaces',
    description: 'Workplaces and retail environments that balance operational clarity with a memorable point of view.',
  },
  {
    id: 'fallback-design-planning',
    title: 'Design & planning',
    description: 'From first sketch to approvals, we turn a clear brief into a buildable plan.',
  },
  {
    id: 'fallback-renovation-restoration',
    title: 'Renovation & restoration',
    description: 'New life for existing structures, retaining their character while making them work harder.',
  },
  {
    id: 'fallback-architectural-design',
    title: 'Architectural design',
    description: 'Illustrative service scope only; confirm current availability and project scope directly with Srinidhi Constructions.',
  },
  {
    id: 'fallback-interior-design',
    title: 'Interior design',
    description: 'Illustrative service scope only; confirm current availability and project scope directly with Srinidhi Constructions.',
  },
  {
    id: 'fallback-structural-engineering',
    title: 'Structural engineering',
    description: 'Illustrative service scope only; confirm current availability and project scope directly with Srinidhi Constructions.',
  },
  {
    id: 'fallback-turnkey-construction',
    title: 'Turnkey construction',
    description: 'Illustrative service scope only; confirm current availability and project scope directly with Srinidhi Constructions.',
  },
  {
    id: 'fallback-project-planning',
    title: 'Project planning and consultation',
    description: 'Illustrative service scope only; confirm current availability and project scope directly with Srinidhi Constructions.',
  },
  {
    id: 'fallback-sustainable-building',
    title: 'Sustainable building solutions',
    description: 'Illustrative service scope only; confirm current availability and project scope directly with Srinidhi Constructions.',
  },
  {
    id: 'fallback-landscape-design',
    title: 'Landscape design',
    description: 'Illustrative service scope only; confirm current availability and project scope directly with Srinidhi Constructions.',
  },
]